name: flutter_inactive_timer
description: "A Flutter plugin for detecting user inactivity in desktop applications (Windows, macOS). Provides customizable timeout and notification thresholds."
version: 1.1.0
homepage: https://github.com/kihyun1998/flutter_inactive_timer
repository: https://github.com/kihyun1998/flutter_inactive_timer
issue_tracker: https://github.com/kihyun1998/flutter_inactive_timer/issues
documentation: https://github.com/kihyun1998/flutter_inactive_timer#readme

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: FlutterInactiveTimerPlugin
      windows:
        pluginClass: FlutterInactiveTimerPluginCApi